

services:
  web-st126686:
    image: tisa99/a2-predicting-car-price:latest
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.routers.web-st126686.rule=Host(`web-st126686.ml.brain.cs.ait.ac.th`)
      - traefik.http.routers.web-st126686.entrypoints=websecure
      - traefik.http.routers.web-st126686.tls=true
      - traefik.http.routers.web-st126686.tls.certresolver=letsencrypt
      - traefik.http.services.web-st126686.loadbalancer.server.port=8050

    networks:
      - web

networks:
  web:
    external: true